<a id="nbtop"></a>
# Exercise: Linear Algebra with Python

## Content:
* [Introduction](#nbintro)
* [Linear algebra operations with Python](#nblinalg)
    * [Creating vectors and matrices](#nbvecmat)
* [Apply learnt methods to solve equations](#nbapply)
* [Better way to solve equations](#nbimprove)
* [Creating a larger "special" matrix](#nbcreate)

<a id="nbintro"></a>
## Introduction
You now have a good understanding of using Python for scientific calculations, so it is time to apply your knowledge to solve reservoir engineering problems with numerical methods!

As discussed in the lecture, the basics steps to solve practical problems, described with partial differential equations, with numerical methods are:

1. Discretise the equation with a suitable method to derive a system of algebraic equations (SAE)
2. Solve that system of algebraic equations for a given set of boundary (and initial) conditions.

Today, we will actually start first with a look at the second step - and the extension to the first step will become clear during the next lecture!

We will first have a look at some basic linear algebra operations and how they can be implemented in Python, and then start to use those methods to solve equations. Finally, we will write a function to create a special type of matrix that we will encounter again in the lecture - and solve this matrix with the discussed methods.

In [1]:
# the basic imports:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

<a id="nbintro"></a>
## Linear algebra operations with Python
The Python module `numpy` contains several methods to perform linear algebra operations. For a complete list, see:

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

Here some important operations:

<a id="nbvecmat"></a>
### Creating vectors and matrices
Vectors can simply be represented as 1-d numpy arrays and matrices as multi-dimensional numpy arrays:

In [2]:
# create vectors as numpy arrays from a Python list:
v1 = np.array([1,2])
v2 = np.array([3,4])
# create a matrix as 2-D numpy array from a nested Python list:
A = np.array([[1,2],[3,4]])

In [3]:
print(v1)
print(A)

[1 2]
[[1 2]
 [3 4]]


We can use a variety of typical operations on these objects. The transpose of a matrix can be obtained with:

In [4]:
# transpose - note: no effect on vector!
print(v1.transpose())
print(A.transpose())

[1 2]
[[1 3]
 [2 4]]


The dot product between two vectors can be calculated with the `numpy.dot` 

In [5]:
print(v1, v2)
print(np.dot(v1, v2))

[1 2] [3 4]
11


**Exercise**: What is the difference between the dot product and a normal multiplication of vectors with the "\*" operator? Try it out:

In [6]:
# your code here:

The dot-product between a vector and a matrix can be calculated with:

In [7]:
print(v1)
print(A)
np.dot(v1,A)

[1 2]
[[1 2]
 [3 4]]


array([ 7, 10])

**Exercise**: what happens if you swap the order in the dot operation? Think about it first - and then try it out. Do you understand what happens?

In [8]:
# your code here

np.dot(A,v1)

array([ 5, 11])

Inner product: `numpy` also contains a method to calculate the general inner product: 
   
    np.inner()
    
**Exercise**: Try out the example of before, but using the inner product instead of the dot product. Can you see the difference? Which important property is different for the two cases?

In [9]:
# your code here


Matrix inversion: the inverse of a matrix can directly be obtained with the `numpy.linalg.inv()` method:

In [10]:
# your code: caluclate inverse of A


For today, we will leave it with symmetrical matrices - more complex cases will come, soon!

<a id="nbapply"></a>
## Applying these methods to solve equations

We can directly use these methods to solve systems of linear equations (if the number of unknowns is equal to the number of equations), i.e.:

$$ a_{11} x_1 + a_{12} x_2 = b_1$$
$$ a_{21} x_1 + a_{22} x_2 = b_2$$

gives us:

$$A x = b$$

**Exercise**: solve this system of the following linear equations using matrix inversion:

$$ -2 x_1 + x_2 = -1$$
$$ x_1 - 2 x_2 = -4$$

In [11]:
# your code here:


Make sure to check if you did get the correct result (hint: make sure you use the dot product for the vector-matrix product):

In [12]:
# your code here:

**Spoiler alert**: Have a look at the result vector `x` that you calculated before: do you observe something interesting? Wait until the next lecture to learn more about it!

<a id="nbimprove"></a>
## Better ways to solve equations
We discussed briefly in the lecture that calculating and using the inverse of a matrix can be very memory-intense and has a limited efficiency (and, in addition, it poses significant problems for high-performance computing on multiple separate computers).

`numpy` contains a dedicated method to solve these systems of equations, the `numpy.linalg.solve()` method. This method is based on routines of the famous computational linear algebra package LAPACK that I mentioned before (http://en.wikipedia.org/wiki/LAPACK).

**Exercise**: use this function to solve the above system of equations:

In [13]:
# your code here


I told you before that you should never trust anyone who claims that a certain code runs faster than another code - so check yourself if my claim above is true:

**Exercise**: use the cell magic function `%%timeit` to compare the execution times for both methods to solve the equation:

What did you observe? Do you have an explanation for this behaviour?

<a id="nbcreate"></a>
## Creating a larger "special" matrix
I still hold up my claim that the method `np.linalg.solve()` is more efficient - just not in the special case above, but for all general cases where we have to deal with matrices that are *a lot* larger than the one we created above!

**Exercise**: To explore this behaviour, here is your task:

1. Write a function that creates a square matrix (N x N) of the form:

$\begin{bmatrix}
-2 & 1 & 0 & 0 & \cdots & 0\\
1 & -2 & 1 &  0 & \cdots & 0\\
0 & 1 & -2 & 1 & \cdots & 0\\
\vdots & & & & & \vdots \\
0 & \cdots & 0 & 1 & -2 & 1 \\
0 & \cdots & 0 & 0 & 1 & -2
\end{bmatrix}$

2. Create an array `b` of length N with b[0] = 10, b[N] = 20, else 0
3. Solve the equation Ax = b with both methods above
4. Time and compare the results

## Extra: yet another way to speed up

If we store the entire matrix in memory, we are in fact requiring a lot of memory space to store elements with no information (zeros), essentially a lot of overhead... and also a limitation, once we go to large matrices, as these will quickly require more memory than any reasonable computer has today. There should be a better way to store all of this information in a compressed form - and there is! 

The idea is to use sparse matrices, and this concept is implemented in the python package `scipy.sparse`:

https://docs.scipy.org/doc/scipy/reference/sparse.html

And here some more information:

https://www.scipy-lectures.org/advanced/scipy_sparse/index.html

In addition with the appropriate solvers, these sparse storage schemes do not only allow us to simulate larger problems, but also lead to an increase in efficiency due to far better memory handling.

**Your task**: try it out: implement the above solution for the tridiagonal matrix using a sparse matrix representation and solver and compare solve time for increasingly large $n$:




In [37]:
import scipy.sparse as sps

In [39]:
import scipy

In [40]:
scipy.__version__


'1.1.0'